server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false    #flase表示不像注册中心注册自己
    fetch-registry: false           #false表示自己就是注册中心,职责就是维护服务实例，并不需要取检索服务
    service-url:
       #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka   #单机版配置
       defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
