server:
  port: 9527
spring:
  application:
    name: clover-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: myzuul.com
    prefer-ip-address: true
info:
  app.name: cloud-study-gateway-9527
  company-name: www.hxd.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  routes:
    mydept.serviceId: clover-dept
    mydept.path: /mydept/**
  ignored-services: CLOVER-DEPT
  prefix: /api