server:
  port: 8011

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.clover.springcloud.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microprovider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: micloud-dept8001hystrix      #自定义服务名称信息
    prefer-ip-address: true            #访问路径可以显示ip地址

info:
  app.name: mscloud-provider-dept8001
  company.name: www.hxd.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

# 配置hystrix dashboard的url访问
# 开启指标流端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream